### ISSUE TITLE
HTTPS oldalon nem jelenik meg az iframe

### ISSUE THREAD

**Issue by SzendreiAdam** [gykhauth/SalesAutopilotPowerUps#1]
HTTPs oldalon hibát ad a chrome, miszerint a HTTPS oldalra HTTP tartalmat akarunk behúzni. 

A php kód utolsó sorát lecserélve megoldható a probléma:

echo str_replace("http","https",$updateformlink);

Hátha segít valakinek.

**Comment by gykhauth** [comment]
@SzendreiAdam Köszönöm, javítottuk. Az API hívás végére kellett egy secure paraméter.
